name: 'custom-action'
description: 'hopefully runs a custom action'
on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: cody-carlson/custom-action@main
        name: custom-action-step
